### ISSUE TITLE
Actividades futuras: no considera la hora

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#102]
# :beetle: Problema detectado

Cuando se sacan los turnos, la lista de actividades muestra “actividades” futuras.
Pareciera que está filtrando ese “futuro” por fecha pero no por horario.
Por ejemplo siendo las 22:21 puedo sacar turnos para actividades que ya se hicieron en el día actual

<img width="970" alt="Turnos - UNaHur" src="https://user-images.githubusercontent.com/39915206/109089408-f2574900-76ef-11eb-8e7e-8af04ff1c0b1.png">

Adicionalmente por el mismo problema al sacar el turno quedan en TURNOS ANTERIORES

# :notebook: Acciones sugeridas

Modificar el llamado que se hace a la API para que solo muestre las actividades futuras, teniendo en cuenta la hora.

# 👩🏽‍💻 Notas para el desarrollo

_Creo_ (habría que probarlo) que se solucionaría mandando en el filtro `desde` la fecha y hora actual en formato ISO - ahora solamente se está enviando la fecha.

**Comment by faloi** [comment]
Ok, aunque habría que hacerlo bien porque para el bedel sí quisieramos que pueda ver todas las del día de hoy (porque ponele que se atrasó o lo que fuera... ya no podría registrar los ingresos).

Mañana le pongo cabeza y sumo algún comentario acá.

**Comment by informaticaUNAHUR** [comment]
¿Ambas vistas usan la misma consulta?
capaz hay que pensar en diferenciar por roles
Es cierto lo del bedel pero lo otro confunde si bien no es crítico

**Comment by faloi** [comment]
Sí, pero podemos diferenciar en el parámetro: que el de asistente mande la hora actual y el de bedel no. Creo que el backend no le da pelota a la hora, sería cuestión de modificar eso también.
