### ISSUE TITLE
No permitir borrar actividades con turnos

### ISSUE THREAD

**Issue by faloi** [unahur-covid/planificacion#103]
# :beetle: Problema detectado

Esta acción no está soportada por el backend, pero el front lo permite a medias. Al intentar borrar salta un error por la consola y no se borra.

# :notebook: Acciones sugeridas

Si la actividad ya tiene algún turno, deshabilitar el tachito y ponerle un [tooltip](https://material-ui.com/components/tooltips/#simple-tooltips) que diga "No se puede borrar esta actividad porque ya tiene turnos asignados".

Si es posible, sería bueno agregarle también tooltips a la acción de editar y a la de borrar cuando está habilitada.

**Comment by JoaquinPettinari** [comment]
Y que le pongo al tooltip cuando está habilitado? Ya hice lo del "No se puede ...."

**Comment by faloi** [comment]
> Y que le pongo al tooltip cuando está habilitado? Ya hice lo del "No se puede ...."

Ponele `Eliminar`, y de paso al lapicito también le podés poner uno que diga `Editar`.
