### ISSUE TITLE
Mejorar preview en redes sociales

### ISSUE THREAD

**Issue by faloi** [unahur-covid/planificacion#108]
# :heavy_check_mark: Objetivos

Mejorar la forma en que se ve la previsualización de nuestra aplicación en redes sociales y aplicaciones de mensajería.

# :technologist: Notas para el desarrollo

Eso se logra metiendo unos tags especiales `<meta>` en el `index.html`. Con poner estos tags creo que sería suficiente:

* `og:title` Turnos UNaHur 
* `og:image` URL del logo a color, sin texto (ver cómo está incluido en los tags que están),
* `og:description` Pedí y consultá tus turnos para realizar actividades presenciales en la Universidad.
* `og:locale` es_AR

# :link: Material útil

[Open Graph Preview](https://chrome.google.com/webstore/detail/open-graph-preview/ehaigphokkgebnmdiicabhjhddkaekgh) - es un plugin para Chrome/Chromium/Brave que sirve para ver cómo se vería la página actual al ser compartida. Con esto se puede probar "en vivo" sin tener que andar compartiendo la URL por ningún lado.

**Comment by FlorenciaMssy** [comment]
No no esta tomando la imagen, si copio el link como esta en los demás tags no se ve en la preview. Si pongo para probar otro link de alguna imagen si se ve, pero con las que hay no. ¿Qué puede ser?

Lo que no funciona: <meta property="og:image" content="%PUBLIC_URL%/apple-touch-icon.png">

**Comment by faloi** [comment]
Mmm, prueben con el logo, no con esa apple touch icon. Igual, armen el pull request y la seguimos ahí sobre el código.
