### ISSUE TITLE
Al editar actividad la fecha fin da error

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#109]
# :beetle: Problema detectado

Al editar una actividad se produce un problema de control de la fecha/hora de fin. Y no le da bola a la edición del campo "activa".

https://user-images.githubusercontent.com/39915206/109163297-f028d500-7757-11eb-9008-c25d1f9d9f3d.mp4

# :notebook: Acciones sugeridas

- ver por qué si están bien cargadas el control falla

**Comment by faloi** [comment]
> Fer dice: lo que tuve que hacer es volver a seleccionar la fecha de inicio

Se me hace que no se está seteando la fecha de inicio en el editar, y por eso la validación falla.
