### ISSUE TITLE
NavBar Asistente: mis turnos queda fijo

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#110]
# :beetle: Problema detectado

La NavBar de Visitante mantiene "marcado" mis turnos cuando se saca una autorización

![03-autorizacion-barra_superior](https://user-images.githubusercontent.com/39915206/109164569-5cf09f00-7759-11eb-8c94-8480d6c5cded.png)

# :notebook: Acciones sugeridas

- Al estar sacando autorización hay que desmarcar la opción Mis Turnos del menú superior

**Comment by faloi** [comment]
Directamente borraría la opción de Solicitar turno, se puede acceder desde la otra pantalla.
