### ISSUE TITLE
API Guaraní - traer carreras aunque no haya inscripciones

### ISSUE THREAD

**Issue by faloi** [unahur-covid/planificacion#112]
# :heavy_check_mark: Objetivos

Poder saber a qué carrera(s) se anotó un estudiante, aún cuando no esté inscripto a ninguna materia.

# :technologist: Notas para el desarrollo

Lo ideal sería que en esos casos el JSON venga igual que ahora pero sin materias. Sería así:

```js
// GET /inscripciones/4614047

{
  id: 11794,
  nombre: 'ALFREDO ',
  apellido: 'Nievas Gomez',
  dni: '4614047',
  carreras: [
    {
      id: 21,
      nombre: 'Tecnicatura universitaria en Informática',
      materias: [],
    },
    {
      id: 38,
      nombre: 'Licenciatura en Informática',
      materias: [],
    },
  ],
}
```

**Comment by clombardi** [comment]
Hola, está en dev, pruébenlón. OJO - **todes** les alumnes de la UNaHur están inscriptes en la carrera 18, que es el curso de preparación, esa carrera nunca se borra. Avisé.

**Comment by faloi** [comment]
Funciona perfecto, cerramos.
