### ISSUE TITLE
Asistente - Controlar cantidad máxima de turnos

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#113]
# :beetle: Problema detectado

se detectó caso en producción idActividad=22 que tiene más inscriptos que aforo

# :notebook: Acciones sugeridas

- verificar control de aforo

**Comment by faloi** [comment]
Además de los repetidos, acá hay un problema de concurrencia (el chequeo se hace antes de que el usuario mande la request para inscribirse).
