### ISSUE TITLE
Asistente - no permitir cancelar un turno ya ingresado

### ISSUE THREAD

**Issue by kenny13a** [unahur-covid/planificacion#116]
# :beetle: Problema detectado

Al ser registrado desde el usuario **BEDEL** el ingreso de un **asistente* el turno queda como "turnos futuros" en el usuario **asistente** por lo que le permite _"cancelar el turno"_ y desaparecer de la lista.

![Peek 26-02-2021 18-52](https://user-images.githubusercontent.com/43205529/109359256-e9878400-7863-11eb-9dd9-2e08ac32833e.gif)

# Lógica :thinking: 
> Si la persona ingresó y cancela el turno estando dentro de la Universidad, aparecerá cómo que su lugar está vacante.

# :notebook: Acciones sugeridas
Una vez que el **BEDEL** registre su ingreso el turno debería pasar a turnos anteriores o a algo así como "ingresado" o desactivar la opción de cancelar turno una vez registrado.

# :technologist: Notas para el desarrollo

Tal vez se pueda hacer que el Bedel pueda cancelar el turno o marcar como que se fue, si el turno dura mucho tiempo y el usuario asistente solo asiste por poco tiempo.

Saludos, Santiago.

**Comment by faloi** [comment]
Muy buena observación. 

En estos casos, haría lo siguiente:
* deshabilitar el botón de `Cancelar turno` 
* cambiarle el texto del botón por `Actividad en curso`
* cambiarle el color por `info` o `success`

El tema de que se vaya antes queda fuera del alcance del sistema.

**Comment by JoaquinPettinari** [comment]
@faloi cuando se desactiva el botón, el color ni se ve. Lo dejo así?
![image](https://user-images.githubusercontent.com/48968618/110391797-c5d3f300-8046-11eb-982f-5612d9948c1c.png)

**Comment by JoaquinPettinari** [comment]
![problemaActividades](https://user-images.githubusercontent.com/48968618/110393141-d08f8780-8048-11eb-8931-cc20632207e9.gif)

Así es la cuestión? Porque puse un notificar al usuarios/yo/turnos pero hasta que no das f5 no se actualiza... está bien?
