### ISSUE TITLE
Cambiar la fecha al cargar una actividad: MUY DIFICIL

### ISSUE THREAD

**Issue by kenny13a** [unahur-covid/planificacion#117]
> Borrar las secciones que no se usen. :smiley:

# :beetle: Problema detectado
Al crear una actividad como **admin**, la validación de la fecha no me deja escribir.
![Peek 26-02-2021 18-27](https://user-images.githubusercontent.com/43205529/109360277-ad552300-7865-11eb-9f5b-d8aa652caff2.gif)
Para poder ingresar la fecha y hora tengo que copiar el formato y cambiar solamente un numero que instantaneamente sea una fecha y hora válida, de lo contrario me salta el mensaje de error.
![Peek 26-02-2021 18-30](https://user-images.githubusercontent.com/43205529/109360352-d5dd1d00-7865-11eb-9327-79c6be4f128c.gif)

# :notebook: Acciones sugeridas

Validlar la fecha y hora solamente al hacer click en el botón crear.
O mejor aún, agregarle un menú desplegable tipo widget que permita seleccionar de un calendario la fecha y hora y evitar problemas de formato.

Saludos, Santiago.

**Comment by faloi** [comment]
@kenny13a entiendo que el desplegable tipo calendario está funcionando, al menos en Chrome. ¿Con qué navegador probaste?

Si usás Firefox, entonces esto es una duplicada de #75.

**Comment by kenny13a** [comment]
> @kenny13a entiendo que el desplegable tipo calendario está funcionando, al menos en Chrome. ¿Con qué navegador probaste?
> 
> Si usás Firefox, entonces esto es una duplicada de #75.

Si, uso Firefox. Está duplicada entonces.
