### ISSUE TITLE
Ordenar actividades como admin

### ISSUE THREAD

**Issue by kenny13a** [unahur-covid/planificacion#118]
# :heavy_check_mark: Objetivos

Poder ordenar el listado de _Actividades_ en el usuario **admin** ya que la lista puede llegar a ser muy extensa y diversa.

# :technologist: Notas para el desarrollo

Se podría agregar alguna forma de filtro y/o forma de ordenar las actividades por _nombre, espacio, responsable, estado, cupo_.
Así si yo deseo ver solamente las actividades del **Aula informática**, por ejemplo, solo debería ordenarla de **A a Z** o filtrar por _espacio_.

Saludos, Santiago.

**Comment by faloi** [comment]
Con #106 y #105 se atacaría bastante este mismo problema.
