### ISSUE TITLE
Gestionar endpoint para interactuar con Guaraní

### ISSUE THREAD

**Issue by faloi** [unahur-covid/planificacion#14]
Esto nos va a ser necesario para poder asignar roles a la hora del registro dentro de nuestro sistema. 

Me imagino un endpoint `GET /inscripciones/36222333` (donde el número representa a un DNI), que devuelva algo de este estilo:

```json
{
  "id": 4444,
  "nombre": "Fulano de tal",
  "dni": "36222333",
  "carreras": [
     {
        "id": 123, 
        "nombre": "Tecnicatura en Informática",
        "materias": [
           { 
             "id": 444, 
             "codigo": "INTRO",
             "nombre": "Introducción a la programación"
           },
           { 
             "id": 445, 
             "codigo": "ORGA",
             "nombre": "Organización de computadoras"
           }
        ]
    }
  ]
}
```

Los ids no me interesan especialmente, pero nos pueden servir si luego tenemos que hacer alguna otra consulta.

Se aceptan sugerencias.

**Comment by clombardi** [comment]
Hola, vamos por ahí. Mockealo nomás. Aviso cuando esté.

**Comment by faloi** [comment]
Bueno, el código ya está terminado. Nos queda de nuestro lado subirlo a algún lado y hacer unas pequeñas pruebas.

**Comment by faloi** [comment]
Quedó disponible en http://cidia.unahur.edu.ar/, y en la [wiki](https://github.com/unahur-covid/planificacion/wiki) hay documentación de los endpoints.
