### ISSUE TITLE
Pantalla de inicio de sesión / registro

### ISSUE THREAD

**Issue by faloi** [unahur-covid/planificacion#26]
# ✅ Objetivo

Implementar la pantalla de inicio de sesión y registro, según lo especificado en Figma

# 👩‍💻 Implementación

Una vez realizado el login, guardar en el estado global de la aplicación la información del usuario. Las requests sucesivas a la API deben hacerse con el token correspondiente.

Por el momento, la parte de _recuperar contraseña_ queda afuera.

Para ver que quede funcionando el estado global, se podría poner en algún lado el nombre del usuario.

# ☝️Dependencias

https://github.com/unahur-covid/backend/issues/3

**Comment by JoaquinPettinari** [comment]
Body Register:
{
    "nombre": "Usuario",
    "apellido": "Uno",
    "contrasenia": "1111",
    "dni": 1,
    "telefono": 1,
    "email": "uno@gmail.com",
    "rol": "invitado"
}

Body login
{
    "dni": 1,
    "contrasenia": "1111"
}

Response registro:
{
    "data": {
        "id": 2,
        "nombre": "Usuario",
        "apellido": "Dos",
        "dni": 2,
        "telefono": 2,
        "email": "dos@gmail.com",
        "rol": "invitado",
        "updatedAt": "2021-01-22T21:51:56.204Z",
        "createdAt": "2021-01-22T21:51:56.204Z"
    }
}

Response login:
{
    "id": 1,
    "nombre": "Usuario",
    "apellido": "Uno",
    "dni": 1,
    "telefono": 1,
    "email": "uno@gmail.com",
    "rol": "invitado",
    "createdAt": "2021-01-22T21:14:49.148Z",
    "updatedAt": "2021-01-22T21:14:49.148Z",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImRuaSI6MSwiaWF0IjoxNjExMzUyMzQ3LCJleHAiOjE2MjY5MDQzNDd9.1bfPflZyw_Gkghs65QCRZuwAjk_73RwNrXhHshsRlf4"
}

**Comment by faloi** [comment]
@JoaquinPettinari me tomé el atrevimiento de formatear tu comentario. 😅 
Fijate que en Postman también están las requests, por si quieren probar.
