### ISSUE TITLE
Mejorar errores del registro que vienen del backend

### ISSUE THREAD

**Issue by faloi** [unahur-covid/planificacion#38]
# :heavy_check_mark: Objetivos

Mostrar mensajes de error más pertinentes cuando hay un error en el registro, por ahora se muestra un mensaje genérico.

# :technologist: Notas para el desarrollo

Ahora el backend devuelve una lista de mensajes de error, pero no dice a qué campos están asociados. Para poder mostrarlo de manera más feliz en el frontend habría que:

1. Modificar el array ese para que sea un hash. En vez de `['El DNI ya está en uso', 'El mail ya está en uso']` debería ser ` { dni: 'El DNI ya está en uso', mail: 'El mail ya está en uso' }.
2. Teniendo ese array en el front, hacer que el error se vea en el o los campos que correspondan.

👀 Ojo: esta issue implica tocar tanto backend como frontend.

**Comment by JoaquinPettinari** [comment]
Eso es así? 
![image](https://user-images.githubusercontent.com/48968618/106386156-6b45d800-63b2-11eb-8bcb-9707e41a2178.png)

**Comment by faloi** [comment]
Eso te va a dar los mensajes, pero hay que cambiar también lo que devuelve el endpoint: ahora hace un map del message y no te dice a qué campo corresponde.

**Comment by faloi** [comment]
Creo que lo que tenemos ahora es suficientemente bueno... si hace falta más adelante reabrimos.
