### ISSUE TITLE
Realizar un prototipo de posibles funcionalidades en Figma

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#4]
**Disponible en [Figma](https://www.figma.com/file/EERBD84KZTeUrndMi3elTq/App_protocolo?node-id=0%3A1).**

## General

Utilizar plantillas con componentes de Material UI.

## Pantallas candidatas

Sujetas a cambios, sugerencias y mejoras, las pantallas que deberían estar son las siguientes. Están ordenadas por rol.

### Estudiante :student: 

**Registro**

Debería pedir DNI, contraseña, nombre, correo electrónico, teléfono y creo que nada más. La idea es que luego validemos el DNI contra Guaraní para ver si es Estudiante o Invitadx.

**Pedido de autorización para realizar una actividad**

En principio, solo le aparecerían las actividades para las cuales puede participar. Lo que interesa particularmente es la pantalla donde envía la solicitud, debería incluir las preguntas de la declaración jurada (medio de transporte, contacto estrecho, etc).

### Bedel :police_officer: 

**Verificación de una autorización (por DNI)**

En principio, una pantalla en la que ingresa el DNI de quien está en la puerta y le dice rápidamente si puede o no ingresar a la facultad, y en el caso de que sí le muestra a qué actividad va.

### Admin :raising_hand_man: 

**Carga de salas**

Nombre, aforo, edificio, etc.

**Carga de actividades**

Responsable/s, fecha-hora inicio, fecha-hora fin, sala en la que ocurrirá.

**Comment by informaticaUNAHUR** [comment]
Respecto de la pantalla de registro me hago esta pregunta: ¿conviene agregar el dato Nro Trámite del DNI (https://formulario-ddjj.argentina.gob.ar/img/version-dni.jpg)? el certificado de circulación de Cuidar lo pide. Es una forma de validar los DNIs que no se usen DNIs de otros... es un dato más  y obviamente uno ese nro no se lo acuerda de memoria , tiene que mirar el plástico...  no sé... pensemos

Agreguemos: email y teléfono en el caso que NO sean estudiantes, porque si hay que ubicar a esas personas, siendo estudiantes tenemos los datos en Guaraní, pero si es INVITADx sería bueno tener algún dato de contacto

**Comment by faloi** [comment]
Está buena la idea del número de trámite, pero habría que ver qué posibilidad real hay de validarlo. Porque si no, estamos en la misma: podés poner cualquier cosa y te dejamos pasar igual.

Email y teléfono podríamos pedirlo siempre, así nos aseguramos de que es el posta. Lo agrego.

**Comment by informaticaUNAHUR** [comment]
La combinación DNI+nro trámite se puede validar contra Renaper (registro Nac de las Personas).
Conozco alguien ahí que quizás nos pueda dar acceso a API
Pero en función de cómo avancemos vemos si sumamos esa comprobación.

**Comment by faloi** [comment]
De acuerdo. Si querés cargalo como issue y le ponemos alguna etiqueta tipo "sería bonito hacerlo" (aka nice to have).

**Comment by faloi** [comment]
Disponible en https://discord.com/channels/656909199510601744/771052564023869440/780622436311498802
