### ISSUE TITLE
Restricción por carrera en Actividad

### ISSUE THREAD

**Issue by faloi** [unahur-covid/planificacion#41]
# :heavy_check_mark: Objetivos

Poder restringir una actividad para que solo puedan inscribirse estudiantes de una cierta carrera.

# :technologist: Notas para el desarrollo

Agregar a la actividad un atributo opcional `restriccionId` que pueda guardar el id de la carrera para la cual fue pensada (ver #22, estos ids salen de la API Guaraní). Luego, al crear una autorización para dicha actividad, hay que verificar que el usuario esté inscripto a esa carrera y devolver un 403 si no lo está (`Unauthorized`).

Para facilitar la inscripción, agregar también un endpoint `/usuarios/yo/actividades`, que devuelva únicamente las actividades a las que ese usuario puede inscribirse (con el mismo filtro de fecha que tiene `/actividades`). Con esto ya se podría quitarle acceso a la ruta `/actividades`, así solo puede ver las que puede realizar.

# :point_up: Dependencias

#22

**Comment by AyelenRdgz** [comment]
Consuta: en el caso que el alumno este inscrito en mas de una carrera?

**Comment by faloi** [comment]
Sería lo mismo, se valida que esté inscriptx a la carrera que la actividad requiere. Ponele, si cursás Enfermería y Programación podés ir a actividades de cualquiera de esas dos carreras.

**Comment by tiago-cabrera** [comment]
Buenas @faloi, tenemos una consulta con respecto al endpoint `/usuarios/yo/actividades`, el dni del usuario va a llegar en el body de la request?

**Comment by faloi** [comment]
No necesitás que llegue como parámetro, porque lo sacás del usuario que está logueado. 

Lo tenés disponible en `req.usuario`.

**Comment by faloi** [comment]
Para esta sí estaría bueno meter un método en el usuario que te devuelva solo las actividades que puede ver.
