### ISSUE TITLE
Luego de completar el registro aparece el siguiente alerta en el navegador

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#43]
# :heavy_check_mark: Problema detectado

Alerta de seguridad del navegador al terminar registro.
Al parecer un control de tipo de contraseña.

![00-bug-registro](https://user-images.githubusercontent.com/39915206/105923834-bdd26d80-601b-11eb-9c03-5b153b47f864.png)

# :technologist: Acciones

- Identificar origen del problema.
- Si es por debilidad de contraseña, agregar validación (May, Min. caracteres. etc.)

**Comment by faloi** [comment]
Evidentemente pusiste una contraseña muy común (tipo 123456) y Chrome detectó que fue vulnerada en algún servicio. Igual no está de más pedir un mínimo de cosas: alguna letra, algún número, longitud mínima de 8 caracteres.

Debería aparecer un texto que diga eso y además validar con una regex que se cumpla.
