### ISSUE TITLE
La opción INICIO de barra de navegación lleva a página login

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#44]
# :heavy_check_mark: Problema detectado

Estando logueado al presionar el botón INICIO lleva a Login.
![01-bug-inicio](https://user-images.githubusercontent.com/39915206/105924202-9a5bf280-601c-11eb-9bbc-c383289424bf.gif)

# :technologist: Acciones 

- Quitar la opción

**Comment by JoaquinPettinari** [comment]
Esto lo veniamos hablando con Fede y elegimos dejarlo así de momento. Para este sprint si me sobra tiempo me hago el home así estamos con eso

**Comment by faloi** [comment]
Coincido con sacar la opción. Incluso lo probé en mobile y se ve mal, al sacar el Container se descompaginó todo. 

Para no perder tiempo, yo cambiaría esto por una responsive drawer de Material que ya sabemos que funciona bien en cualquier dispositivo.

**Comment by faloi** [comment]
Ya se corrigió.
