### ISSUE TITLE
Carga de actividad: no hay respuesta ni mensaje 

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#45]
# :heavy_check_mark: Problema detectado

En pantalla de carga de actividades, si se presiona GUARDAR sin completar nada, no se produce ninguna respuesta visual.
Ni campos destacados obligatorios, ni mensaje de error.
Se completaron Nombre y Espacio y persiste error (parece que API necesita todos los campos)

![02-bug-carga-actividad](https://user-images.githubusercontent.com/39915206/105924693-92508280-601d-11eb-9e26-1b5befa56b54.gif)

# :technologist: Acciones

- Agregar validaciones mínimas: Nombre, Espacio deben estar completos
- Responsable y DNI responsable NO deben ser OBLIGATORIOS (parece que el backend da error si esto no se completa)
- Control de fechas

**Comment by faloi** [comment]
Faltaría resolver esto en el back:

> Responsable y DNI responsable NO deben ser OBLIGATORIOS (parece que el backend da error si esto no se completa)
