### ISSUE TITLE
UI: diferentes criterios de alineación y ubicación de botones

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#48]
# :heavy_check_mark: Problema detectado

En cada pantalla se siguen criterios distintos de colores, alineación y ubicación de elementos de la UI

![00-bug-botones 001](https://user-images.githubusercontent.com/39915206/106020131-324fef80-60a2-11eb-870b-2a5fcbb5580f.jpg)

# :technologist: Acciones

- Definir criterio y unificar

# :link: Material útil

Este material me pareció oportuno. Es de balsamiq que es algo como Figma pero dan algunos criterios piolas
[Designing for Action: Best Practices for Effective Buttons](https://balsamiq.com/learn/articles/button-design-best-practices/#6-full-page-designs-should-have-the-primary-button-on-the-left-side-of-the-page)

**Comment by faloi** [comment]
Acá hay algo más sobre los botones, de la guía oficial de Material Design: https://material.io/components/buttons#hierarchy-and-placement.
