### ISSUE TITLE
Armar modelo de datos mínimo

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#5]
Disponible en [Lucidchart](https://lucid.app/lucidchart/invitations/accept/26389b5d-74a0-4dc7-8699-2778fd26689a).

**Entidades candidatas:**

* Actividad
* Sala
* Autorización
* Estudiante

**Comment by GerezPablo** [comment]
[Link al diagrama](https://lucid.app/lucidchart/invitations/accept/26389b5d-74a0-4dc7-8699-2778fd26689a)

**Comment by faloi** [comment]
Cierro esta, creo que ya no tiene sentido actualizar ese diagrama.
