### ISSUE TITLE
Unificar selector de actividad

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#53]
# :heavy_check_mark: Problema detectado

Si bien es un campo de autocompletar y a medida que se escribe se van filtrando las actividades (eso está perfecto), en la lista confunde un poco que esté el nombre y el horario.

![Captura de Pantalla 2021-02-02 a la(s) 17 34 24](https://user-images.githubusercontent.com/39915206/106659255-3d60bf00-657d-11eb-8198-bc4de945e2f9.png)

# :technologist: Acciones

Reutilizar el componente que está en control de acceso, teniendo la precaución de que para la pantalla del asistente tiene que deshabilitar las actividades sin lugares disponibles y para la del bedel no.

Además, agregarle a ese componente fecha y hora de la actividad, me imagino que en una línea nueva puede quedar bien.

**Comment by faloi** [comment]
Como sugirió @CabreraTiago, acá podemos usar el componente que está en control de acceso.

**Comment by faloi** [comment]
En línea con #54, le agregaría también algún texto de ayuda para que el usuario se avive de que puede escribir.
