### ISSUE TITLE
Unificar mensajes y validaciones

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#54]
# :heavy_check_mark: Problema detectado

Hay diferentes criterios en los mensajes

![03-bug-autorizacion-lenguaje](https://user-images.githubusercontent.com/39915206/106677782-21b6e200-6598-11eb-8a5c-56919c101708.png)

# :technologist: Acciones

-Unificar criterios: utilizar el criterio marcado como correcto en la imagen
- Revisar en toda la aplicación

**Comment by faloi** [comment]
Habría que mirar también en las validaciones.

**Comment by faloi** [comment]
Acordamos entonces que vamos a usar:

* para mensajes, validaciones y ayudas de input, el voseo imperativo: "hacé tal cosa", "seleccioná tal otra", "recordá hacer aquello", 
* para botones, verbos en infinitivo: "Guardar", "Cancelar", "Volver al inicio",
* para etiqueta de campos de un formulario, nombre del atributo: "Nombre", "Horario de inicio", "Contraseña".

Desde ahora en adelante deberíamos tener esto en cuenta para los pull requests también.
