### ISSUE TITLE
Registro: clave inválida impide saber formato

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#55]
# :heavy_check_mark:  Problema detectado

Si bien al registrarse se indica el formato de la clave que hay que usar, si uno se equivoca o no coinciden las claves se marca error pero se pierde la referencia del formato que hay que seguir.
Eso puede hacer que uno intente muchas veces por desconocer cantidad de chars, formato, etc

![00-bug-registro_pwd](https://user-images.githubusercontent.com/39915206/106678305-3051c900-6599-11eb-8976-2c6d6a9b4b94.gif)

# :technologist: Acciones

- Marcar el error pero mantener el texto que indica el formato correcto a usar

**Comment by faloi** [comment]
Creo que lo más sencillo es que el mensaje de error también diga cuál es el formato esperado.

**Comment by faloi** [comment]
@informaticaUNAHUR no se llega a ver en el GIF: ¿el mensaje de "Las contraseñas no coinciden" dónde está? Debería ir en el campo de confirmación, no en el de contraseña.

**Comment by informaticaUNAHUR** [comment]
1) Este es el mensaje cuando uno empieza la registración
![Captura de Pantalla 2021-02-03 a la(s) 12 48 02](https://user-images.githubusercontent.com/39915206/106771797-21f9c080-661e-11eb-9ead-61ff5547cef2.png)

2) Si se pone mal la clave (mal el formato o no coincide con "confirmar contraseña" sale así y ya no se puede saber cómo era el formato correcto

![Captura de Pantalla 2021-02-03 a la(s) 12 49 26](https://user-images.githubusercontent.com/39915206/106771997-566d7c80-661e-11eb-9cbf-6e00a8de5866.png)

NOTA: capaz cuando se vuelve a tipear debe "desaparecer el error rojo" y volver el texto en gris (ver punto 1)

**Comment by JoaquinPettinari** [comment]
Buenas, como va? Así les parece? 
![image](https://user-images.githubusercontent.com/48968618/107443130-fe031700-6b16-11eb-8bc3-1d406bcf1f2d.png)
