### ISSUE TITLE
Autorización: explicación adicional

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#56]
# :heavy_check_mark: Problema detectado

A nivel de usuario es bueno que ciertos campos tengan información adicional que explique su sentido/uso

![03-autorizacion-explicar](https://user-images.githubusercontent.com/39915206/106769129-62a40a80-661b-11eb-980b-bdad8aba2c7b.png)

# :technologist: Acciones

- Agregar ToolTip o algún recurso con referencia de (?) ayuda que permita aclarar estos campos
- Seleccione Actividad --> debe ser "Seleccioná" y para ese caso sería bueno complementar con: "Podés ir tipeando el tipo de actividad a la que querés acceder y se filtra según la disponibilidad."
- Para el campo Medio de Transporte el complemento sería: "Indicá cómo pensás movilizarte hasta la universidad cuando vayas a realizar la actividad"

**Comment by faloi** [comment]
> Seleccione Actividad --> debe ser "Seleccioná" y para ese caso sería bueno complementar con: "Podés ir tipeando el tipo de actividad a la que querés acceder y se filtra según la disponibilidad."

De hecho me parece que el "seleccione" es redundante, porque ya está en el stepper. Con poner `Actividad` creo que ya se entiende perfectamente.

**Comment by faloi** [comment]
> Agregar ToolTip o algún recurso con referencia de (?) ayuda que permita aclarar estos campos

Ojo que el ToolTip ya probamos que en mobile es medio difícil de ver, y justamente esta pantalla es la que más se va a utilizar desde ese tipo de dispositivos. Quizás pueda hacerse con un helperText.

**Comment by informaticaUNAHUR** [comment]
Sí, la forma más adecuado que encontremos. Puse esa opción como referencia pero puede ser otra. Sé que estuvieron experimentando con el campo de Password. 
Efectivamente esto será lo más usado y por eso hay que explicarlo muy bien.
Creo que incluso al ser el paso 1 de 2 campos solamente se pueden agregar Textos fijos Antes de cada uno. Eso ayudaría mucho.
