### ISSUE TITLE
Control de acceso: está mal la pantalla de inicio

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#58]
# :beetle: Problema detectado

Al iniciar sesión como Bedel (control de acceso) por defecto queda la pantalla de inicio de sesión y para ir al control específicamente hay que presionar en el botón CONTROL DE ACCESO

![04-contro-acceso_inicio](https://user-images.githubusercontent.com/39915206/106770942-3ab5a680-661d-11eb-88c9-1cd9c683b367.gif)

# :notebook: Acciones sugeridas

-Siendo que este rol por ahora tiene una sola acción que la pantalla de inicio sea el CONTROL DE ACCESO propiamente dicho.

**Comment by faloi** [comment]
Se resuelve junto a la #52.
