### ISSUE TITLE
El selector de actividades muestra las inactivas

### ISSUE THREAD

**Issue by faloi** [unahur-covid/planificacion#63]
# :beetle: Problema detectado

Si bien el admin tiene la posibilidad de marcar una actividad como inactiva, eso no tiene ningún efecto sobre la aplicación.

# :notebook: Acciones sugeridas

Resolverlo a nivel de backend.

# :technologist: Notas para el desarrollo

* Renombrar el atributo `estado` a `activa`, que refleja mejor lo que representa (hay que hacer una migra y cambiar el nombre en el frontend).
* Modificar el endpoint `/actividades` para que, por defecto, solamente devuelva aquellas que tenga `activa = true`.
* Agregarle un query param al endpoint `/actividades` para que también devuelva las inactivas, podría ser `actividades?inactivas=true`.
* Modificar el listado de actividades que ve el admin para que sí incluya las actividades inactivas.

**Comment by tiago-cabrera** [comment]
![image](https://user-images.githubusercontent.com/48968913/108584175-fe24c300-731d-11eb-9c1a-c1ce4babce20.png)

¿Acá lo cambiamos a `Activa:` `Si` `No` o lo dejamos como está?

**Comment by faloi** [comment]
Dejémoslo así por ahora, si vemos que no se entiende modificamos.
