### ISSUE TITLE
Borrar el navbar para el bedel, el footer y hacer que el logo redirija al inicio

### ISSUE THREAD

**Issue by faloi** [unahur-covid/planificacion#65]
# :heavy_check_mark: Objetivos

Mejorar la navegación de la aplicación, dejando la barra de navegación únicamente para los roles asistente y admin.

# 👩🏽‍💻 Notas para el desarrollo

Dejar la navegación que está ahora, solamente para el admin y el asistente. Los demás roles solo pueden navegar lo que las pantallas les permitan. 

Convertir el logo en un link que lleve a la ruta inicial del rol (eso ya está hecho con un selector de Recoil).

**Comment by informaticaUNAHUR** [comment]
En la reunión que tuve hoy con Prensa de la universidad y la gente de Diseño Industrial que está trabajando en comunicación y señalética una de las cosas que surgió es que quizás en el ROL Asistente se agrega alguna info a modo de opción de menú (navegación) sobre CIRCULACIÓN por ejemplo una imagen con croquis indicando lugar de acceso y algo sobre temas del protocolo.
Me parece que deberíamos entonces mantener el Navbar para Asistentes también y tener:
- Autorizaciones: como dijimos, listado y botón de SACARA nueva Autorización
- Circulación: por ahora solamente la opción pero van a poner algo
- Protocolo: idem circulación

**Comment by AyelenRdgz** [comment]
Dejo este comentario para que no se me olvide de consultar: en el caso de los alumnos, que solo van a pedir autorización, me parece que seria conveniente que tambien tengan una pantalla de: autorizaciones solicitadas, no solo para que puedan ver los turnos que sacaron sino tambien para poder cancelarlos. Nada, lo puse aca por la idea de borrarles el NavBar, capaz habría que tenerlo en cuenta.

**Comment by faloi** [comment]
La pantalla que dice @Pepitalapistolera está planificada para la #62. Faltaría lo de cancelar turnos, lo anoto como idea para más adelante si nos da el tiempo.

De todos modos, el NavBar al final va a quedar por esas dos pantallas de información general que mencionó Fer.
