### ISSUE TITLE
Instalar infraestructura Backend en Producción

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#67]
# :heavy_check_mark: Objetivos

Configurar infraestructura de Backend en VMs Google Cloud provistas por UNAHUR

# :technologist: Notas para el desarrollo

Seguir este modelo
![image](https://user-images.githubusercontent.com/39915206/107047380-85165f00-67a6-11eb-9e49-4af1a177b036.png)

- Instalar Postgres
- Instalar NodeJS
- Instalar CLI Git (Debería estar con el S.O por defecto)

# :link: Material útil

https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04

**Comment by informaticaUNAHUR** [comment]
Se instaló:

1) postgres=# SHOW server_version;
            server_version             
 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1)

2) nginx -v
nginx version: nginx/1.14.0 (Ubuntu)

3) nodejs -v
v14.15.5
npm -v
6.14.11

**Comment by informaticaUNAHUR** [comment]
Actualizada versión Postgres
psql (12.5 (Ubuntu 12.5-1.pgdg18.04+1))
Type "help" for help.

**Comment by informaticaUNAHUR** [comment]
* Se instaló PM2
* Se configuró Script para arrancar tarea NPM desde PM2 y tener control del proceso incluyendo variables de entorno
```/home/pryecto/pm2-server.config.js```

* Se configuró HOOK post-receive para deployar de ambiente local a Server de producción
```/home/proyecto/covid-api/hooks/post-receive```

* Queda deployado y se ejecuta desde:
```/var/www/covid-api```

**Comment by faloi** [comment]
Creo que por ahora estamos. Lo que podríamos es meter esas configuraciones en un repo privado así no se pierden.

Para más adelante, tal vez se pueda usar [PM2 deployments](https://pm2.keymetrics.io/docs/usage/deployment/), que tiene como principal ventaja que se pueden correr los comandos de pm2 sin tener que conectarse por SSH a la VM (lo maneja el mismo pm2).

**Comment by faloi** [comment]
Creado el repo, cerramos esto por ahora.
