### ISSUE TITLE
Un mismo asistente puede pedir varias autorizaciones para la misma actividad

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#69]
# :beetle: Problema detectado

Es posible solicitar muchas veces la misma actividad
Se muestra pantalla de Control de Acceso con 

![03-bug-autoizaciones-multiples](https://user-images.githubusercontent.com/39915206/107542678-32261880-6ba7-11eb-8ff4-d4f0ff59e2b5.png)

Esto incluso puede tener impacto en el AFORO

# :notebook: Acciones sugeridas

- Controlar que solo se pueda solicitar una sola vez acceso a la misma actividad por usuario

# ☝🏽 Dependencias

#41

**Comment by faloi** [comment]
Lo más fácil sería excluir las actividades para las cuales ya solicitó autorización de la lista. 

Alcanzaría con modificar el endpoint `/usuarios/yo/actividades` para que no incluya aquellas para las cuales ya pidió autorización.

**Comment by faloi** [comment]
Por las dudas, también tirar un 400 si ya tenía una autorización para esa actividad.
