### ISSUE TITLE
Mejorar visibilidad de los botones en los listados

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#76]
# :beetle: Problema detectado

Si la cantidad de actividades o espacios va creciendo, los listados se hacen muy largos para visualizar.
Esto incluso hace que para cargar una nueva actividad sea necesario scrollear mucho
![02-bug-carga-actividad-listado_largo](https://user-images.githubusercontent.com/39915206/107891834-e0132900-6eff-11eb-8dbd-ab259a2657ee.png)

# :notebook: Acciones sugeridas

Como primeras medidas se propone:
- mover o replicar arriba del listado la opción de "Agregar..."
- Ordenar los listados de "más nuevo a más viejo"

Como opciones ideales a trabajar:

-Paginar
- Poder cambiar el orden y filtrar al menos por fecha

**Comment by faloi** [comment]
Creo que lo podríamos resolver con un [Floating action button](https://material-ui.com/components/floating-action-button/), que es lo que Material sugiere (y varios sitios conocidos ya usan).
