### ISSUE TITLE
Selector de Actividades Ordenado

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#79]
# :beetle: Problema detectado

la lista de actividades que ve el asistente o el bedel (Selector de Actividades) aparece en orden de carga y esto no ayuda a seleccionar rápidamente

# :notebook: Acciones sugeridas

- Ordenar las listas de Actividades de los SELECTORES (Visitantes, Bedel)
- Ordenar por fecha más reciente en la que se va a realizar la actividad y luego alfabéticamente por nombre de la actividad

**Comment by faloi** [comment]
Ambos endpoints `/actividades` y `/usuarios/yo/actividades` deberían venir ordenados según el criterio que puso Fer. Resolverlo a nivel SQL, no en memoria.
