### ISSUE TITLE
Reflotar footer

### ISSUE THREAD

**Issue by faloi** [unahur-covid/planificacion#93]
# :heavy_check_mark: Objetivos

Comunicar que la aplicación fue realizada por estudiantes.

# :technologist: Notas para el desarrollo

Agregar un texto debajo de todo, con algún color no muy llamativo (por ejemplo, gris). Nada raro: un texto que solo se ve cuando llegás al final.

Yo pondría esto:

> Esta aplicación ha sido realizada por estudiantes de la Licenciatura en Informática de la UNaHur. Se permite su uso, modificación y distribución bajo los términos de la [licencia GPLv3](https://www.gnu.org/licenses/gpl-3.0.html).
>
> Si encontraste algún error o querés ver el código fuente, podés acceder a la [organización de GitHub del proyecto](https://github.com/unahur-covid).

**Comment by JoaquinPettinari** [comment]
Falta y el nombre de los creadores.

**Comment by faloi** [comment]
> Falta y el nombre de los creadores.

Eso se ve acá: https://github.com/unahur-covid/frontend/graphs/contributors
😉
