### ISSUE TITLE
Enviar mail cuando se registra un usuario

### ISSUE THREAD

**Issue by faloi** [unahur-covid/planificacion#95]
# :heavy_check_mark: Objetivos

Notificar al usuario de que su cuenta ha sido creada.

# :technologist: Notas para el desarrollo

Luego de registrarse, debería enviarse un email genérico de bienvenida.

Para poder reutilizar esto en #89, conviene hacer un objeto `MailSender` o similar, que tenga todo lo necesario para mandar un mail. 

Agregar variables de entorno para todas las configuraciones necesarias (probablemente solo usuario y contraseña).

# 📎 Links útiles

https://nodemailer.com/smtp/

**Comment by faloi** [comment]
https://blog.mailtrap.io/nodemailer-gmail/

**Comment by faloi** [comment]
Otra opción es esto que pasó Fer:

```
Servidor SMTP: smtp.gmail.com
Usuario SMTP: Tu usuario de Gmail completo (email), por ejemplo tuemail@gmail.com
Contraseña SMTP: Tu contraseña de Gmail.
Puerto SMTP: 587
TLS/SSL: Requerido.
```

**Comment by clombardi** [comment]
Hola, un avisito: nosotros enviamos los mails usando el servicio de mail de la Universidad, que se llama MailJet. Usando MailJet, no es difícil meter imágenes en el mail. Y además se encarga de que los mails no queden señalados como spam, y salen con remitente @unahur.edu.ar. Incluuuuuso se podríiiia hacer que el sistema de turnos use al sistema retención para mandar mails, así como lo está usando para pedir datos de Guaraní. Hablemos si les interesa.

**Comment by faloi** [comment]
Habíamos evaluado usarlo pero nos bajamos porque la gestión para conseguir las credenciales parecía difícil. Pero con este nuevo escenario, habría que pensarlo mejor.

**Comment by clombardi** [comment]
Si usan retención, se los podríamos hacer en dos semanas, o sea lo tendrían (siendo un poco conservador) a ppios de abril. ¿Les sirve?

**Comment by informaticaUNAHUR** [comment]
Si quieren hablo con Melina... y lo pido. Teniendo CIDIA conocimiento de uso es un buen paso

**Comment by informaticaUNAHUR** [comment]
De cualquier forma me parece que la cantidad de emails que enviará esta App es muy baja. Y la verdad que usar o no imágenes no creo que cambie mucho la cosa.

**Comment by clombardi** [comment]
Como querráis. No se me ocurre un escenario en que Melina diga que no, tiene contratado un millón de mails por mes.

**Comment by clombardi** [comment]
Igualmente ... tal vez el día que le digan a les estudiantes de Kinesiología que tienen que sacar turnos x la app ... tal vez se inscriban unes cuantes (dato de contexto: Kinesio tenía 5202 estudiantes registrados al 20/05/2020)

**Comment by informaticaUNAHUR** [comment]
Sí, pero el Campus debe enviar por día cuando comience la cursa cerca de 50000, Hoy le pregunto

**Comment by informaticaUNAHUR** [comment]
Ya inicié gestiones... En tal caso nos respondan que sí ¿Carlos vos le podés decir a alguien del equipo que en la semana de una mano? Vienen atrasadísimas. 2 issues que usan esto:  avisar del registro y recuperar clave

**Comment by clombardi** [comment]
Justo están todes con tareas asignadas, y es medio choto cortar a mitad de
una tarea. Confirmen primero, y después veo cómo nos podemos acomodar.

**Comment by faloi** [comment]
El mail no es crítico para nuestra aplicación, solo se va a usar en el registro y si eventualmente pierden la contraseña. No mandamos mails para nada más.

Viendo que esto ya quedó andando (hay un PR dando vueltas que aún no miré), no cambiaría a MailJet ahora.
